<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>Mailpox</title>
    <style>
        :root{--navy:#243b53;--teal:#15959f;--line:#d9e2ec;--muted:#627d98;--bg:#f5f7fa;--danger:#d64545}*{box-sizing:border-box}html,body{margin:0;height:100%;font:14px/1.45 system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:#102a43;background:var(--bg)}a{color:inherit;text-decoration:none}.navbar{height:52px;background:var(--navy);color:#fff;display:flex;align-items:center;padding:0 18px;gap:18px}.brand{font-size:20px;font-weight:700}.search{flex:1;max-width:680px}.input{width:100%;border:1px solid var(--line);border-radius:4px;padding:9px 11px;background:#fff}.button{border:1px solid var(--line);background:#fff;border-radius:4px;padding:8px 12px;cursor:pointer}.button-danger{color:#fff;background:var(--danger);border-color:var(--danger)}.layout{height:calc(100vh - 52px);display:grid;grid-template-columns:390px minmax(0,1fr)}.sidebar{overflow:auto;background:#fff;border-right:1px solid var(--line)}.toolbar{display:flex;gap:8px;padding:10px;border-bottom:1px solid var(--line)}.message-row{display:block;padding:11px 14px;border-bottom:1px solid var(--line)}.message-row:hover,.message-row.active{background:#e8f4f6}.message-row.unread{font-weight:700}.message-head{display:flex;justify-content:space-between;gap:10px}.message-subject{white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.message-meta{color:var(--muted);font-size:12px;margin-top:3px}.content{min-width:0;overflow:auto}.empty{display:grid;place-items:center;height:100%;color:var(--muted)}.detail-header{background:#fff;border-bottom:1px solid var(--line);padding:18px}.detail-actions{float:right;display:flex;gap:8px}.detail-grid{display:grid;grid-template-columns:90px 1fr;gap:5px 12px;margin-top:12px;color:var(--muted)}.tabs{display:flex;background:#fff;border-bottom:1px solid var(--line)}.tab{padding:12px 16px;border:0;background:transparent;cursor:pointer}.tab.active{border-bottom:3px solid var(--teal);color:var(--teal)}.panel{display:none;padding:18px}.panel.active{display:block}.preview{width:100%;height:calc(100vh - 245px);border:0;background:#fff}.source{white-space:pre-wrap;word-break:break-word;background:#fff;padding:18px;border:1px solid var(--line)}.attachments{display:flex;gap:8px;flex-wrap:wrap;margin-top:15px}.attachment{padding:8px 10px;border:1px solid var(--line);border-radius:4px;background:#fff}.notice{padding:8px 14px;background:#d9f2e6;color:#185c37}.pagination{padding:12px;display:flex;justify-content:space-between}@media(max-width:800px){.layout{grid-template-columns:1fr}.sidebar:has(+ .content .detail-header){display:none}.content{height:100%}.detail-grid{grid-template-columns:60px 1fr}}
    </style>
</head>
<body>
<nav class="navbar"><span class="brand">📨 Mailpox</span><form class="search" action="{{ route('mailpox.index') }}"><input class="input" name="search" value="{{ $search }}" placeholder="Search mailbox"></form></nav>
@if(session('mailpox_status'))<div class="notice">{{ session('mailpox_status') }}</div>@endif
@yield('content')
<script>const mailpoxPollingInterval={{ max(0, (int) config('mailpox.polling_interval', 5)) * 1000 }};const mailpoxPollUrl=@json(route('mailpox.poll'));if(mailpoxPollingInterval>0){setInterval(async()=>{if(document.hidden)return;try{const url=new URL(mailpoxPollUrl,window.location.origin);const search=new URLSearchParams(window.location.search).get('search');const selected=document.querySelector('.message-row.active')?.dataset.messageId;if(search)url.searchParams.set('search',search);if(selected)url.searchParams.set('selected',selected);const response=await fetch(url,{headers:{Accept:'application/json'},cache:'no-store'});if(!response.ok)return;const state=await response.json();const list=document.getElementById('mailpox-message-list');const count=document.getElementById('mailpox-message-count');if(list)list.innerHTML=state.html;if(count)count.textContent=`${state.count} messages`}catch(error){}},mailpoxPollingInterval)};</script>
<script>document.querySelectorAll('[data-tab]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('.tab,.panel').forEach(el=>el.classList.remove('active'));button.classList.add('active');document.getElementById(button.dataset.tab).classList.add('active')}));document.querySelectorAll('[data-confirm]').forEach(form=>form.addEventListener('submit',event=>{if(!confirm(form.dataset.confirm))event.preventDefault()}));</script>
</body>
</html>
